### ISSUE TITLE
Zapier Integration

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#10]

**Comment by ijunaid8989** [comment]
Follow up:

I am going to add the same interface as for other integrations, where User will have to add its zap's webhook and choose the Emotions to send to this webhook, Then EOT web app will only send an object with emotion and jpeg to Zap.

**Comment by marcoherbst** [comment]
@JaviCT will create the Zapier App and manage this task. It may require more work from @ijunaid8989

**Comment by JaviCT** [comment]
@marcoherbst @ijunaid8989 
I am thinking about how to integrate zapier with EoT and what authentication method we should use. We have this options: https://zapier.com/developer/documentation/v2/authentication/

I think we can use the API key and when we click on "Integrate with zapier" on EoT website generate the key that we are going to use to authenticate with zapier.

For the moment, I create a zap that is going to ask you for the device  MAC and are going to return the image, id and the emotion captured. If we create the API key authentication we are not going to need to insert the MAC when we create the zap

**Comment by marcoherbst** [comment]
Happy with this. Thanks Guys.
