### ISSUE TITLE
Share options other than just to Public Feed ( FB , Whatsapp, Linkedin  ....)

### ISSUE THREAD

**Issue by josemariar** [EyesOfThings/Mobile_Camera_Demonstrator#19]
Each image includes a icon similar to the ones used for sharing, but it does not work at all. What is its functionality?

**Comment by marcoherbst** [comment]
Take influence from these sites:
https://project1-evercam.herokuapp.com/image-editor/example01-basic.html
http://ogp.me/

**Comment by ijunaid8989** [comment]
its done.
