### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#24]
Why is Javier's Device on the same account as the other one ... ?

**Comment by ijunaid8989** [comment]
Current structure is:

![image](https://user-images.githubusercontent.com/13561999/40470329-a12c9c50-5f4c-11e8-9599-116377a24ee0.png)

There is only one device listed and all jpegs are being saved under this one. 

There should be another structure/ tree for separate device or email to show them in different view.

**Comment by marcoherbst** [comment]
This might be for @JaviCT on his return.

**Comment by marcoherbst** [comment]
@javict .... I think this is related, right?

**Comment by JaviCT** [comment]
Yes, it is also fixed, now we have different devices with different account
