### ISSUE TITLE
Date Filter Not Working

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#25]

**Comment by ijunaid8989** [comment]
![image](https://user-images.githubusercontent.com/13561999/41078171-8483367a-6a34-11e8-99e9-275c6e8d6874.png)


Its working for me unless you have an example to show.

![image](https://user-images.githubusercontent.com/13561999/41078190-a343a8f6-6a34-11e8-9f52-fa5962449a86.png)

**Comment by marcoherbst** [comment]
You're right, it's working. Though I think we need From & To Dates. Look for a very nice way of doing this (look for a nice interface .... it is a chance to find something beautiful that could then be used in Evercam)

**Comment by JaviCT** [comment]
Also we have a wrong date on the list view and that is the date picked by the filter:
![image](https://user-images.githubusercontent.com/19703794/41860034-7e067194-7895-11e8-8b1f-1390e097b00c.png)

And the right date is this:
![image](https://user-images.githubusercontent.com/19703794/41859927-38105772-7895-11e8-8fbc-ec7a351d7eba.png)

**Comment by ijunaid8989** [comment]
@JaviCT It wasn't a bug actually, It was different date formats, I have fixed this now, Both dates are being displayed in the same format.

**Comment by ijunaid8989** [comment]
Its done, I have added 2 date range filter for it.
