### ISSUE TITLE
Public feed should not ask login

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#28]
?? I think ... that makes sense, right?

Then the URL must change from /feed to /{username}   , right?

**Comment by ijunaid8989** [comment]
it's done. now it's /feed/UID. also added error message in case of the wrong uid passed.

**Comment by marcoherbst** [comment]
Yes/No, when I go to the public feed:

http://eot.evercam.io/feed/fc0AxWAW70dUseZVXFzppY5uWoX2

It asks me to login.

M

**Comment by ijunaid8989** [comment]
There are many issues with having no authentication in here.
We are using user's email, who have been logged in to get all Database Structure tree, Its full name in Menu, and UID, these all things are not public, they only come to you when the user is authenticated.

If there will be no authentication, We don't even have the email through which User has been logged in and have all data structure tree in firebase. these all information is coming after user login.

**Comment by marcoherbst** [comment]
I leave it with you to sort that out. "Public Feed" is a public feed ... visible to the public. :)

My guess is that you will, like with animations, be putting a copy of the images somewhere else, though there may be more elegant solutions.

**Comment by marcoherbst** [comment]
If, in the process of solving this you use the user's email as their UserID, that's good for me. Consider Email to be equivalent to username and not confidential (like in Evercam)

m

**Comment by ijunaid8989** [comment]
Login has been removed from public feed now. But user's email is going as a query parameter like this

http://eot.evercam.io/feed?email=visilabeot@gmail.com

Because rails route don't allow to have a full email address if you pass it as /feed/email@address.com

it came as email@address as a parameter, which is not right.
