### ISSUE TITLE
Wrong Text on share by twitter.

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#29]
It says:
This is a photo from evercam http://bit.ly/2sIWG0z via @evrcm

It should say:

This is a photo from Eyes of Things: http://bit.ly/2sIWG0z !

... I've not yet looked at the others, but check them too.

**Comment by ijunaid8989** [comment]
done.

**Comment by marcoherbst** [comment]
Nope

![image](https://user-images.githubusercontent.com/5648894/41085564-55bd8ea8-6a2f-11e8-9dcd-b234a4c6eabf.png)

**Comment by ijunaid8989** [comment]
![image](https://user-images.githubusercontent.com/13561999/41086352-3b9ef1f0-6a53-11e8-8f06-439165004d37.png)

**Comment by ijunaid8989** [comment]
its done.
