### ISSUE TITLE
There seem to be  /Images and /Images2 in the DB. One is probably not needed?

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#31]
![image](https://user-images.githubusercontent.com/5648894/41026320-29f4d4d4-696c-11e8-9e73-8f0ecbe84f8c.png)

**Comment by ijunaid8989** [comment]
Images2 is not needed, as from the start all jpegs are being uploaded to `images/` and also path is being saved as `images/{unixtimestamp}.jpg`

**Comment by marcoherbst** [comment]
@espiaran @odeniz  , I will delete the /images2 folder, ok?
M

**Comment by josemariar** [comment]
Images2 folder is not necessary, if I remember correctly, it was created by Javier to test it

**Comment by marcoherbst** [comment]
Thanks. 

@ijunaid8989 , please remove it.

**Comment by ijunaid8989** [comment]
Removed.
