### ISSUE TITLE
Remove the Device Selection Screen. Replace with a SELECT box.

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#33]
The default option on the select box (visible) is the selected option. e.g. "All" or " { MAC } " ... ( remove "Device" text)

**Comment by marcoherbst** [comment]
- [ ] Should allow Multiple

- [ ] OR, if that's hard (more than 4 hours) then don't and instead, where it says "Devices" show the currently select

ed radio option. I'd be equally happy with that.

**Comment by ijunaid8989** [comment]
its done.
