### ISSUE TITLE
Wizard send email with wrong images

### ISSUE THREAD

**Issue by JaviCT** [EyesOfThings/Mobile_Camera_Demonstrator#40]
Thanks @JaviCT  , can we have a screenshot & description?

**Comment by JaviCT** [comment]
On that file, the email and MAC is caught from the code, it should be the the user logged. Right now if I login with javier@evercam.io I get an email with the images of the account visilabeot@gmail.com
https://github.com/EyesOfThings/Mobile_Camera_Demonstrator/blob/065cc5319b0721f117de96d607efcb5f384be3bf/app/models/wizard.rb#L27

![image](https://user-images.githubusercontent.com/19703794/41529817-3a07f760-72e6-11e8-96b8-b68d122070f2.png)

**Comment by ijunaid8989** [comment]
Thanks for pointing it out, there is an option to replace email and mac with the logged in user, Will be fixed soon.

**Comment by ijunaid8989** [comment]
Its done.
