### ISSUE TITLE
Performance Issues with too many images

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#41]
@ijunaid8989 find a way to deal with this.

**Comment by ijunaid8989** [comment]
@marcoherbst details? On the main screen?

**Comment by marcoherbst** [comment]
Try it. You'll see.

**Comment by ijunaid8989** [comment]
I have deployed a version with such solution as:

When It will load, don't append all the jpegs coming from devices but just append 10 first and then on each scroll append 9, 9 jpegs view with the DOM. it may reduce the performance issues.

**Comment by ijunaid8989** [comment]
It's done.
