### ISSUE TITLE
Action: Create Animation

### ISSUE THREAD

**Issue by marcoherbst** [EyesOfThings/Mobile_Camera_Demonstrator#8]
1. Select images
2. Create Animation.
3. View animation under "Animations" in left nav (use Video.JS player).

**Comment by ijunaid8989** [comment]
I have consulted with @azharmalik3, 

what is the requirement here?

1: You want to show animation only on runtime as User is on the page, after that it's not available. then we can use Jquery Plugin.

2: If user is going to see his created animations after sign out or page refresh and then we need to do server side work using FFMPEG and then save the animation to seaweedFS under the name of device, where we are saving images for device

**Comment by ijunaid8989** [comment]
its done and deployed.
